// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmpvwowofrfdzhtnrukz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtcHZ3b3dvZnJmZHpodG5ydWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDk4ODMsImV4cCI6MjA2OTcyNTg4M30.bSDCAd-SEslTcbqtznDC1KQic3oZqMFWMxdwIsKfA5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});